#!/usr/bin/env python3
"""浏览器脚本生成器。

将录制转换为可执行的Shell脚本和配置文件。

用法:
    python generator.py --recording login_github
    python generator.py --recording login_github --output ~/.copaw/browser_scripts/
    python generator.py --recording login_github --force
"""

import argparse
import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# 添加父目录到路径以导入copaw模块
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))

from copaw.constant import get_request_working_dir

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def get_recordings_dir() -> Path:
    """获取录制存储目录。"""
    working_dir = get_request_working_dir()
    return working_dir / "browser_recordings"


def get_scripts_dir() -> Path:
    """获取脚本输出目录。"""
    working_dir = get_request_working_dir()
    scripts_dir = working_dir / "browser_scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    return scripts_dir


def load_recording(name: str) -> Dict[str, Any]:
    """加载录制数据。"""
    recording_path = get_recordings_dir() / name
    recording_file = recording_path / "recording.json"

    if not recording_file.exists():
        raise FileNotFoundError(f"Recording '{name}' not found at {recording_file}")

    with open(recording_file, "r", encoding="utf-8") as f:
        return json.load(f)


def load_metadata(name: str) -> Dict[str, Any]:
    """加载元数据。"""
    recording_path = get_recordings_dir() / name
    metadata_file = recording_path / "metadata.json"

    if metadata_file.exists():
        with open(metadata_file, "r", encoding="utf-8") as f:
            return json.load(f)
    else:
        # 返回默认元数据
        return {
            "name": name,
            "description": f"浏览器操作脚本: {name}",
            "parameters": [],
            "cli_command": name.replace("_", "-"),
        }


def generate_shell_script(
    recording: Dict[str, Any],
    metadata: Dict[str, Any],
) -> str:
    """生成Shell脚本内容。"""
    name = recording["name"]
    description = metadata.get("description", f"浏览器操作脚本: {name}")
    parameters = metadata.get("parameters", [])
    cli_command = metadata.get("cli_command", name.replace("_", "-"))

    # 生成脚本头部
    script_lines = [
        "#!/bin/bash",
        f"# Generated by browser_cli skill",
        f"# Description: {description}",
        f"# Created: {datetime.now(timezone.utc).isoformat()}",
        "",
        "set -e",
        "",
    ]

    # 生成参数变量声明
    script_lines.append("# Parameters")
    for param in parameters:
        param_name = param["name"]
        default_value = param.get("default", "")
        script_lines.append(f'{param_name.upper()}="{default_value}"')

    script_lines.append("HEADLESS=true")
    script_lines.append("")

    # 生成参数解析
    script_lines.append("# Parse arguments")
    script_lines.append("while [[ $# -gt 0 ]]; do")
    script_lines.append("    case $1 in")

    for param in parameters:
        param_name = param["name"]
        cli_flag = param.get("cli_flag", f"--{param_name}")
        cli_short = param.get("cli_short", "")
        param_desc = param.get("description", param_name)

        if cli_short:
            script_lines.append(f"        {cli_flag}|{cli_short})")
        else:
            script_lines.append(f"        {cli_flag})")
        script_lines.append(f"            {param_name.upper()}=\"$2\"")
        script_lines.append("            shift 2")
        script_lines.append("            ;;")

    script_lines.append("        --headed)")
    script_lines.append("            HEADLESS=false")
    script_lines.append("            shift")
    script_lines.append("            ;;")

    # 生成帮助信息
    script_lines.append("        --help|-h)")
    help_lines = ['            echo "Usage: $0"']
    for param in parameters:
        param_name = param["name"]
        cli_flag = param.get("cli_flag", f"--{param_name}")
        param_desc = param.get("description", param["name"])
        required = param.get("required", False)
        req_marker = " (必需)" if required else ""
        help_lines.append(f'            echo "  {cli_flag}  {param_desc}{req_marker}"')

    help_lines.append('            echo "  --headed        显示浏览器窗口"')
    help_lines.append("            exit 0")
    script_lines.extend(help_lines)
    script_lines.append("            ;;")

    script_lines.append("        *)")
    script_lines.append("            echo \"Unknown option: $1\"")
    script_lines.append("            exit 1")
    script_lines.append("            ;;")
    script_lines.append("    esac")
    script_lines.append("done")
    script_lines.append("")

    # 生成必需参数验证
    script_lines.append("# Validate required parameters")
    for param in parameters:
        if param.get("required", False):
            param_name = param["name"]
            cli_flag = param.get("cli_flag", f"--{param_name}")
            script_lines.append(f'if [[ -z "${param_name.upper()}" ]]; then')
            script_lines.append(f'    echo "Error: {cli_flag} is required"')
            script_lines.append("    exit 1")
            script_lines.append("fi")

    script_lines.append("")

    # 生成执行命令
    script_lines.append("# Execute browser script")
    script_lines.append("SCRIPT_DIR=\"$(dirname \"$0\")\"")
    script_lines.append("")

    # 构建runner.py调用命令
    cmd_parts = [
        'python "$SCRIPT_DIR/runner.py"',
        f'    --recording {name}',
    ]

    for param in parameters:
        param_name = param["name"]
        cmd_parts.append(f'    --param {param_name}="${param_name.upper()}"')

    cmd_parts.append('    ${HEADLESS:+--headless}')

    script_lines.append(cmd_parts[0])
    for part in cmd_parts[1:]:
        script_lines.append(part)

    script_lines.append("")
    script_lines.append("echo \"Script execution completed\"")

    return "\n".join(script_lines)


def generate_script_config(
    recording: Dict[str, Any],
    metadata: Dict[str, Any],
) -> Dict[str, Any]:
    """生成脚本配置JSON。"""
    return {
        "name": recording["name"],
        "description": metadata.get("description", ""),
        "cli_command": metadata.get("cli_command", recording["name"].replace("_", "-")),
        "parameters": metadata.get("parameters", []),
        "recording_path": str(get_recordings_dir() / recording["name"]),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "total_steps": recording.get("total_steps", 0),
    }


def generate_script(
    name: str,
    output_dir: Optional[Path] = None,
    force: bool = False,
) -> Dict[str, Any]:
    """生成Shell脚本。"""
    # 加载录制和元数据
    try:
        recording = load_recording(name)
        metadata = load_metadata(name)
    except FileNotFoundError as e:
        return {
            "ok": False,
            "error": str(e),
        }

    # 检查录制状态
    if recording.get("status") != "completed":
        return {
            "ok": False,
            "error": f"Recording '{name}' is not completed. Use recorder.py --stop first.",
        }

    # 确定输出目录
    scripts_dir = output_dir or get_scripts_dir()

    # 生成文件路径
    script_file = scripts_dir / f"{name}.sh"
    config_file = scripts_dir / f"{name}.json"

    # 检查是否已存在
    if script_file.exists() and not force:
        return {
            "ok": False,
            "error": f"Script '{name}.sh' already exists. Use --force to overwrite.",
        }

    # 生成脚本内容
    script_content = generate_shell_script(recording, metadata)
    config_content = generate_script_config(recording, metadata)

    # 写入文件
    with open(script_file, "w", encoding="utf-8") as f:
        f.write(script_content)

    # 设置脚本可执行权限
    script_file.chmod(0o755)

    with open(config_file, "w", encoding="utf-8") as f:
        json.dump(config_content, f, indent=2, ensure_ascii=False)

    # 复制runner.py到脚本目录（如果不存在）
    runner_src = Path(__file__).parent / "runner.py"
    runner_dst = scripts_dir / "runner.py"
    if not runner_dst.exists() and runner_src.exists():
        import shutil
        shutil.copy(runner_src, runner_dst)
        runner_dst.chmod(0o755)

    logger.info(f"Generated script '{name}.sh' at {scripts_dir}")

    return {
        "ok": True,
        "name": name,
        "script_path": str(script_file),
        "config_path": str(config_file),
        "total_steps": recording.get("total_steps", 0),
        "parameters": len(metadata.get("parameters", [])),
        "message": f"Script '{name}' generated successfully",
    }


def list_scripts() -> Dict[str, Any]:
    """列出所有生成的脚本。"""
    scripts_dir = get_scripts_dir()
    scripts = []

    if scripts_dir.exists():
        for path in scripts_dir.iterdir():
            if path.suffix == ".sh":
                config_file = path.with_suffix(".json")
                if config_file.exists():
                    with open(config_file, "r", encoding="utf-8") as f:
                        config = json.load(f)
                    scripts.append({
                        "name": config.get("name", path.stem),
                        "cli_command": config.get("cli_command", ""),
                        "description": config.get("description", ""),
                        "total_steps": config.get("total_steps", 0),
                        "parameters": len(config.get("parameters", [])),
                        "script_path": str(path),
                    })

    return {
        "ok": True,
        "scripts": scripts,
        "total": len(scripts),
    }


def main():
    parser = argparse.ArgumentParser(
        description="浏览器脚本生成器",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--recording",
        type=str,
        help="录制名称",
    )
    parser.add_argument(
        "--output",
        type=str,
        help="输出目录",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="强制覆盖已存在的脚本",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="列出所有生成的脚本",
    )
    parser.add_argument(
        "--user-id",
        type=str,
        default=None,
        help="用户ID（多用户隔离）",
    )

    args = parser.parse_args()

    # 设置用户ID（如果提供）
    if args.user_id:
        import copaw.constant
        copaw.constant._request_user_id = args.user_id

    result: Dict[str, Any]

    if args.list:
        result = list_scripts()

    elif args.recording:
        output_dir = Path(args.output) if args.output else None
        result = generate_script(args.recording, output_dir, args.force)

    else:
        result = {"ok": False, "error": "Use --recording <name> to generate script, or --list to show all scripts"}

    # 输出结果
    print(json.dumps(result, indent=2, ensure_ascii=False))

    if not result.get("ok", False):
        sys.exit(1)


if __name__ == "__main__":
    main()